"""
Hierarchical fallback defaults for missing cell values.
Loads cell_defaults.json (generated by sql/generate_defaults.py) and provides
a lookup function that tries increasingly broad groups to find an estimate.

Fallback hierarchy (most specific → least specific):
    1. manufacturer + chemistry  (e.g. Samsung|NMC)
    2. chemistry + format        (e.g. NMC|cylindrical)
    3. chemistry                 (e.g. NMC)
    4. format                    (e.g. cylindrical)
    5. manufacturer              (e.g. Samsung)
    6. global median             (across all cells)
    7. hardcoded emergency value (only if JSON not loaded)
"""

import os
import json
from typing import Optional

# Load the defaults JSON once at import time
_DEFAULTS_PATH = os.path.join(os.path.dirname(__file__), "cell_defaults.json")
_DEFAULTS: dict = {}

if os.path.exists(_DEFAULTS_PATH):
    with open(_DEFAULTS_PATH, "r", encoding="utf-8") as f:
        _DEFAULTS = json.load(f)

# Emergency hardcoded fallbacks (used ONLY if cell_defaults.json doesn't exist)
_EMERGENCY_DEFAULTS: dict[str, float] = {
    "capacity_ah_nom": 5.0,
    "voltage_nom_v": 3.6,
    "voltage_max_v": 4.2,
    "voltage_min_v": 2.5,
    "energy_wh": 18.0,
    "mass_kg": 0.070,
    "dcir_10s_ohms": 0.020,
    "acir_ohms": 0.015,
    "length_mm": 65.0,
    "width_diameter_mm": 21.0,
    "height_mm": 70.0,
    "volume_l": 0.025,
    "discharge_amps_max": 30.0,
    "discharge_amps_cont": 10.0,
    "discharge_temp_max_c": 60.0,
    "discharge_temp_min_c": -20.0,
    "charge_amps_max": 5.0,
    "charge_amps_cont": 3.0,
    "charge_temp_max_c": 45.0,
    "charge_temp_min_c": 0.0,
    "cycles_to_80_soh": 800,
    "cycles_to_70_soh": 1200,
    "wh_per_kg": 250.0,
    "wh_per_litre": 650.0,
}


def get_fallback(
    field: str,
    chemistry: Optional[str] = None,
    format: Optional[str] = None,
    manufacturer: Optional[str] = None,
) -> Optional[float]:
    """Look up a fallback value using the hierarchy.

    Args:
        field: The column name (e.g. 'mass_kg', 'dcir_10s_ohms')
        chemistry: Cell chemistry (e.g. 'NMC', 'LFP')
        format: Cell format (e.g. 'cylindrical', 'prismatic')
        manufacturer: Cell manufacturer (e.g. 'Samsung SDI')

    Returns:
        Best available estimate, or None if no data exists at all.
    """
    if not _DEFAULTS:
        return _EMERGENCY_DEFAULTS.get(field)

    # Level 1: manufacturer + chemistry
    if manufacturer and chemistry:
        key = f"{manufacturer}|{chemistry}"
        val = _DEFAULTS.get("by_manufacturer_chemistry", {}).get(key, {}).get("medians", {}).get(field)
        if val is not None:
            return val

    # Level 2: chemistry + format
    if chemistry and format:
        key = f"{chemistry}|{format}"
        val = _DEFAULTS.get("by_chemistry_format", {}).get(key, {}).get("medians", {}).get(field)
        if val is not None:
            return val

    # Level 3: chemistry only
    if chemistry:
        val = _DEFAULTS.get("by_chemistry", {}).get(chemistry, {}).get("medians", {}).get(field)
        if val is not None:
            return val

    # Level 4: format only
    if format:
        val = _DEFAULTS.get("by_format", {}).get(format, {}).get("medians", {}).get(field)
        if val is not None:
            return val

    # Level 5: manufacturer only
    if manufacturer:
        val = _DEFAULTS.get("by_manufacturer", {}).get(manufacturer, {}).get("medians", {}).get(field)
        if val is not None:
            return val

    # Level 6: global median
    val = _DEFAULTS.get("global", {}).get(field)
    if val is not None:
        return val

    # Level 7: emergency hardcoded
    return _EMERGENCY_DEFAULTS.get(field)


def get_fallback_for_cell(
    field: str,
    cell,
) -> Optional[float]:
    """Convenience wrapper — extracts chemistry/format/manufacturer from a CellCandidate.

    Usage in pipeline:
        from ..defaults import get_fallback_for_cell
        mass = cell.mass_kg or get_fallback_for_cell("mass_kg", cell)
    """
    return get_fallback(
        field=field,
        chemistry=getattr(cell, "chemistry", None),
        format=getattr(cell, "format", None),
        manufacturer=getattr(cell, "manufacturer", None),
    )


def is_loaded() -> bool:
    """Check if cell_defaults.json was loaded successfully."""
    return bool(_DEFAULTS)


def get_hierarchy_info() -> dict:
    """Return info about what's available in the loaded defaults."""
    if not _DEFAULTS:
        return {"loaded": False, "source": "emergency hardcoded defaults only"}
    meta = _DEFAULTS.get("_meta", {})
    return {
        "loaded": True,
        "generated_from": meta.get("generated_from", "unknown"),
        "chemistry_groups": list(_DEFAULTS.get("by_chemistry", {}).keys()),
        "format_groups": list(_DEFAULTS.get("by_format", {}).keys()),
        "combo_groups": list(_DEFAULTS.get("by_chemistry_format", {}).keys()),
        "manufacturer_groups": list(_DEFAULTS.get("by_manufacturer", {}).keys()),
    }
